(defparameter *phrase-synonyms*
  '(("loss of taste and smell" . "loss_of_taste_smell")
    ("loss of taste" . "loss_of_taste_smell")
    ("loss of smell" . "loss_of_taste_smell")
    ("cant taste anything" . "loss_of_taste_smell")
    ("cant smell anything" . "loss_of_taste_smell")
    ("cant taste" . "loss_of_taste_smell")
    ("cannot taste" . "loss_of_taste_smell")
    ("cant smell" . "loss_of_taste_smell")
    ("cannot smell" . "loss_of_taste_smell")
    ("shortness of breath" . "difficulty_breathing")
    ("difficulty breathing" . "difficulty_breathing")
    ("trouble breathing" . "difficulty_breathing")
    ("hard to breathe" . "difficulty_breathing")
    ("cannot breathe well" . "difficulty_breathing")
    ("pain in my chest" . "chest_pain")
    ("pain in chest" . "chest_pain")
    ("chest pain" . "chest_pain")
    ("tight chest" . "chest_tightness")
    ("chest tightness" . "chest_tightness")
    ("tightness in my chest" . "chest_tightness")
    ("heavy chest" . "chest_tightness")
    ("high fever" . "fever")
    ("low grade fever" . "fever")
    ("elevated temperature" . "fever")
    ("feverish" . "fever")
    ("dry cough" . "cough")
    ("chesty cough" . "cough")
    ("hacking cough" . "cough")
    ("coughing" . "cough")
    ("runny nose" . "runny_nose")
    ("stuffy nose" . "runny_nose")
    ("blocked nose" . "runny_nose")
    ("nasal congestion" . "runny_nose")
    ("sore throat" . "sore_throat")
    ("scratchy throat" . "sore_throat")
    ("throat pain" . "sore_throat")
    ("body aches" . "body_aches")
    ("body ache" . "body_aches")
    ("muscle aches" . "body_aches")
    ("aching all over" . "body_aches")
    ("very tired" . "fatigue")
    ("low energy" . "fatigue")
    ("worn out" . "fatigue")
    ("head pain" . "headache")
    ("my head hurts" . "headache")
    ("itchy eyes" . "itchy_eyes")
    ("irritated eyes" . "itchy_eyes")
    ("watery eyes" . "watery_eyes")
    ("teary eyes" . "watery_eyes")
    ("burning when i pee" . "painful_urination")
    ("burning when i urinate" . "painful_urination")
    ("pain when i pee" . "painful_urination")
    ("painful urination" . "painful_urination")
    ("burning urination" . "painful_urination")
    ("frequent urination" . "frequent_urination")
    ("peeing often" . "frequent_urination")
    ("urinating often" . "frequent_urination")
    ("need to pee often" . "frequent_urination")
    ("going to the bathroom a lot" . "frequent_urination")
    ("lower abdominal pain" . "lower_abdominal_pain")
    ("lower belly pain" . "lower_abdominal_pain")
    ("pain in my lower abdomen" . "lower_abdominal_pain")
    ("dry mouth" . "dry_mouth")
    ("mouth feels dry" . "dry_mouth")
    ("reduced urination" . "reduced_urination")
    ("not peeing much" . "reduced_urination")
    ("peeing less" . "reduced_urination")
    ("urinating less" . "reduced_urination")
    ("very thirsty" . "thirst")
    ("feeling thirsty" . "thirst")
    ("cant stop drinking water" . "thirst")
    ("persistent vomiting" . "persistent_vomiting")
    ("keep throwing up" . "persistent_vomiting")
    ("cant keep anything down" . "persistent_vomiting")
    ("throwing up repeatedly" . "persistent_vomiting")
    ("throwing up" . "vomiting")
    ("throw up" . "vomiting")
    ("feeling nauseous" . "nausea")
    ("feel nauseous" . "nausea")
    ("stomach cramps" . "abdominal_cramps")
    ("abdominal cramps" . "abdominal_cramps")
    ("belly cramps" . "abdominal_cramps")
    ("loose stools" . "diarrhea")
    ("light headed" . "dizziness")
    ("lightheaded" . "dizziness")
    ("light headedness" . "dizziness")
    ("mentally confused" . "confusion")
    ("feeling confused" . "confusion")))

(defparameter *word-synonyms*
  '(("fever" . "fever")
    ("temperature" . "fever")
    ("hot" . "fever")
    ("cough" . "cough")
    ("coughing" . "cough")
    ("sneeze" . "sneezing")
    ("sneezes" . "sneezing")
    ("sneezing" . "sneezing")
    ("runny" . "runny_nose")
    ("stuffy" . "runny_nose")
    ("congested" . "runny_nose")
    ("fatigue" . "fatigue")
    ("tired" . "fatigue")
    ("exhausted" . "fatigue")
    ("drained" . "fatigue")
    ("headache" . "headache")
    ("migraine" . "headache")
    ("aches" . "body_aches")
    ("achy" . "body_aches")
    ("aching" . "body_aches")
    ("throat" . "sore_throat")
    ("itchy" . "itchy_eyes")
    ("watery" . "watery_eyes")
    ("nausea" . "nausea")
    ("nauseous" . "nausea")
    ("queasy" . "nausea")
    ("vomit" . "vomiting")
    ("vomiting" . "vomiting")
    ("diarrhea" . "diarrhea")
    ("diarrhoea" . "diarrhea")
    ("cramps" . "abdominal_cramps")
    ("dizzy" . "dizziness")
    ("dizziness" . "dizziness")
    ("confused" . "confusion")
    ("confusion" . "confusion")
    ("thirsty" . "thirst")
    ("breathless" . "difficulty_breathing")))

(defparameter *stopwords*
  '("a" "about" "also" "am" "and" "are" "as" "at" "been" "but" "do" "feel" "feeling" "for"
    "from" "get" "getting" "had" "has" "have" "having" "i" "im" "i'm" "in" "is" "it" "just"
    "like" "lot" "lots" "many" "more" "much" "my" "of" "on" "really" "sense" "some" "than"
    "the" "to" "too" "usual" "very" "when" "with"))

(defun canonical-inventory ()
  (dedupe-preserving-order
   (append
    (mapcar #'cdr *phrase-synonyms*)
    (mapcar #'cdr *word-synonyms*))))
