(defparameter *phrase-synonyms*
  '(("high fever" . "fever")
    ("feverish" . "fever")
    ("coughing" . "cough")
    ("dry cough" . "cough")
    ("runny nose" . "runny_nose")
    ("stuffy nose" . "runny_nose")
    ("nasal congestion" . "runny_nose")
    ("body aches" . "body_aches")
    ("body ache" . "body_aches")
    ("sore throat" . "sore_throat")
    ("itchy eyes" . "itchy_eyes")
    ("watery eyes" . "watery_eyes")
    ("loss of taste and smell" . "loss_of_taste_smell")
    ("loss of taste" . "loss_of_taste_smell")
    ("loss of smell" . "loss_of_taste_smell")
    ("can't taste" . "loss_of_taste_smell")
    ("cannot taste" . "loss_of_taste_smell")
    ("can't smell" . "loss_of_taste_smell")
    ("cannot smell" . "loss_of_taste_smell")
    ("shortness of breath" . "difficulty_breathing")
    ("difficulty breathing" . "difficulty_breathing")
    ("trouble breathing" . "difficulty_breathing")
    ("chest pain" . "chest_pain")
    ("tight chest" . "chest_tightness")
    ("chest tightness" . "chest_tightness")
    ("painful urination" . "painful_urination")
    ("burning urination" . "painful_urination")
    ("burning when i pee" . "painful_urination")
    ("burning when i urinate" . "painful_urination")
    ("frequent urination" . "frequent_urination")
    ("peeing often" . "frequent_urination")
    ("need to pee often" . "frequent_urination")
    ("lower abdominal pain" . "lower_abdominal_pain")
    ("lower belly pain" . "lower_abdominal_pain")
    ("stomach cramps" . "abdominal_cramps")
    ("abdominal cramps" . "abdominal_cramps")
    ("dry mouth" . "dry_mouth")
    ("reduced urination" . "reduced_urination")
    ("not peeing much" . "reduced_urination")
    ("very thirsty" . "thirst")
    ("feeling thirsty" . "thirst")
    ("persistent vomiting" . "persistent_vomiting")
    ("throwing up" . "vomiting")
    ("throw up" . "vomiting")))

(defparameter *word-synonyms*
  '(("fever" . "fever")
    ("temperature" . "fever")
    ("cough" . "cough")
    ("coughing" . "cough")
    ("sneeze" . "sneezing")
    ("sneezing" . "sneezing")
    ("runny" . "runny_nose")
    ("nose" . "runny_nose")
    ("fatigue" . "fatigue")
    ("tired" . "fatigue")
    ("exhausted" . "fatigue")
    ("headache" . "headache")
    ("migraine" . "headache")
    ("aches" . "body_aches")
    ("achy" . "body_aches")
    ("throat" . "sore_throat")
    ("itchy" . "itchy_eyes")
    ("watery" . "watery_eyes")
    ("nausea" . "nausea")
    ("nauseous" . "nausea")
    ("vomit" . "vomiting")
    ("vomiting" . "vomiting")
    ("diarrhea" . "diarrhea")
    ("diarrhoea" . "diarrhea")
    ("cramps" . "abdominal_cramps")
    ("dizzy" . "dizziness")
    ("dizziness" . "dizziness")
    ("confused" . "confusion")
    ("confusion" . "confusion")
    ("thirsty" . "thirst")
    ("breathless" . "difficulty_breathing")))

(defparameter *stopwords*
  '("a" "also" "am" "and" "are" "been" "feel" "feeling" "have" "high" "i" "im" "i'm" "is" "it"
    "just" "lot" "lost" "many" "much" "my" "need" "of" "really" "sense" "some" "the" "to" "very"
    "when" "with"))

(defun sanitize-char (character)
  (if (or (alpha-char-p character) (digit-char-p character) (char= character #\Space))
      (char-downcase character)
      #\Space))

(defun normalize-text (text)
  (let* ((lowered (map 'string #'sanitize-char text))
         (pieces (remove "" (split-sequence #\Space lowered) :test #'string=)))
    (format nil "~{~a~^ ~}" pieces)))

(defun split-sequence (delimiter text)
  (labels ((walk-parts (index current result)
             (cond
               ((>= index (length text))
                (nreverse (cons (coerce (nreverse current) 'string) result)))
               ((char= (char text index) delimiter)
                (walk-parts (1+ index) '() (cons (coerce (nreverse current) 'string) result)))
               (t
                (walk-parts (1+ index) (cons (char text index) current) result)))))
    (walk-parts 0 '() '())))

(defun dedupe-preserving-order (items)
  (labels ((walk-dedupe (remaining seen result)
             (if (null remaining)
                 (nreverse result)
                 (let ((item (car remaining)))
                   (if (member item seen :test #'string=)
                       (walk-dedupe (cdr remaining) seen result)
                       (walk-dedupe (cdr remaining) (cons item seen) (cons item result)))))))
    (walk-dedupe items '() '())))

(defun phrase-matches (normalized-text)
  (labels ((covered-by-existing-p (phrase accepted)
             (some
              (lambda (accepted-entry)
                (search phrase (first accepted-entry) :test #'char=))
              accepted))
           (collect-matches (remaining accepted)
             (if (null remaining)
                 (nreverse accepted)
                 (let* ((entry (car remaining))
                        (phrase (car entry))
                        (canonical (cdr entry)))
                   (if (and (search phrase normalized-text :test #'char=)
                            (not (covered-by-existing-p phrase accepted)))
                       (collect-matches (cdr remaining) (cons (list phrase canonical) accepted))
                       (collect-matches (cdr remaining) accepted))))))
    (collect-matches *phrase-synonyms* '())))

(defun phrase-words (phrase-results)
  (dedupe-preserving-order
   (apply #'append
          (mapcar
           (lambda (phrase-result)
             (split-sequence #\Space (first phrase-result)))
           phrase-results))))

(defun token-matches (tokens)
  (remove nil
          (mapcar
           (lambda (token)
             (let ((match (assoc token *word-synonyms* :test #'string=)))
               (when match
                 (cdr match))))
           tokens)))

(defun unknown-terms (tokens phrase-results)
  (let ((matched-words (phrase-words phrase-results)))
  (remove-if
   (lambda (token)
     (or (assoc token *word-synonyms* :test #'string=)
         (member token *stopwords* :test #'string=)
         (member token matched-words :test #'string=)))
   tokens)))

(defun read-input ()
  (with-output-to-string (buffer)
    (loop for line = (read-line *standard-input* nil nil)
          while line do
            (write-string line buffer)
            (write-char #\Space buffer))))

(defun normalize-input (raw-text)
  (let* ((normalized-text (normalize-text raw-text))
         (tokens (remove "" (split-sequence #\Space normalized-text) :test #'string=))
         (phrase-results (phrase-matches normalized-text))
         (phrase-canonicals (mapcar #'second phrase-results))
         (token-canonicals (token-matches tokens))
         (canonical-symptoms
           (dedupe-preserving-order (append phrase-canonicals token-canonicals))))
    (list
     :canonical-symptoms canonical-symptoms
     :matched-phrases phrase-results
     :unknown-terms (dedupe-preserving-order (unknown-terms tokens phrase-results)))))

(let ((input (read-input)))
  (format t "~s~%" (normalize-input input)))
